title: "澳洲法律笔记 AU Legal Notes"
author: "邓益健 Yijian Deng"
description: "Lawyer of the Supreme Court of New South Wales"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%d %B, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title:Home Change, icon:home}
  - {file: "README.md", title:About me, incon:address-card}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:dengyijian2012@gmail.com"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/yijian_deng"}
  - {title: Work, icon: office, url: "https://www.rzlawyers.com.au"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
